# Default values for kasten-k10-deployment
# This is a YAML-formatted file.

k10:
  # Kasten K10 configuration
  auth:
    tokenAuth:
      enabled: true
  
  # Ingress configuration
  ingress:
    create: false
    host: ""
    tls:
      enabled: false
      secretName: ""
  
  # Persistence configuration
  persistence:
    storageClass: "gp2"
    size: "20Gi"
  
  # Service account configuration
  serviceAccount:
    create: true
    annotations: {}# Updated Sun Nov  9 12:50:08 CET 2025
# Updated Sun Nov  9 12:52:16 CET 2025
# Updated Sun Nov  9 12:56:43 CET 2025
